creation_rules:
    - path_regexp: \.(yml|yaml)$
      encrypted_regex: ^(.*[Pp]assword.*)$
      age: >-
        age1pvk6dvp7zwwmzlknzc8gqzrk4yygmpa35ze20jcf8scuk48lhqdsevf6jx
    - path_regexp: .*/nested\/.*\.(yaml|yml)$
      encrypted_regex: ^(.*[Nn]h.*)$
      age: >-
        age1pvk6dvp7zwwmzlknzc8gqzrk4yygmpa35ze20jcf8scuk48lhqdsevf6jx
