#!/usr/bin/env python3
import subprocess
import argparse
import sys
import re
import os

CWD=""
SOPS_CONFIG_PATH=""
files=[]

def run_command(command):
    """Utility function to run a shell command."""
    subprocess.run(command, shell=True)

parser = argparse.ArgumentParser(description='Decrypt files using sops.')
parser.add_argument('-f', '--filename', help='Filename to decrypt', required=False)
args = parser.parse_args()

if args.filename:
    file_path = args.filename
    if os.path.isfile(file_path):
        files.append(file_path)
    else:
        print(f"invalid file path: {file_path}")
        sys.exit(1)
else:
    for root, dirs, files in os.walk(CWD):
        for file in files:
            if file.endswith((".yaml", ".yml")):
                files.append(os.path.join(root, file))

for file in files:
    # exclude .sops config file
    if re.search(r'\.sops\.y(a)?ml$', file):
        continue
    print(f"decrypting file: {file}")
    # run_command()
    # capture_output=False, check=True, text=True
    subprocess.run(f"sops -d -i '{file}'", shell=True)