apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: john-carlson
    nh: ENC[AES256_GCM,data:E9P3KT4=,iv:rlyVNkg+HkWvZ+gIFw/JEL6EmBEQhTULUmdJA1vhwmE=,tag:5LppSlUevkXS4LyDPMJcrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10uuwjxr0x0ge4mm2c7u3hm207dwc4jpwe46gtfk2c5kusqtg55ds0jr4uv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Q3hGZWNUb3ZXa1RFT0Ni
            eHlJMFdrVlE4VXFkTjd2WEw3ZEY0ME9CQno0CjBqZElsWEVUd0x3eGd6c1FweDla
            R3NGeTN1ejlTZDN4a0Urakd5WGxxeEkKLS0tIHdTMjgrZklIT1pON1p3Ymxnb0Qv
            dGVRMzZqZmtuMnRaZUhFVFAraElxTjAK0Abkn00eZOJyUaEKd2uFMVYB+BVlHoYv
            9+Z5GViphVs517qkz1Uo6yXAXCtGs4pVVnUB++8+rpH4RFHNlJW8pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T08:14:34Z"
    mac: ENC[AES256_GCM,data:yERo8rV+LBcIPR+9udPPAc+fOsRFrClFnrjCnjenXzH9UehCARcMzm3g0sLRCnTQGk7RALdvB3sE9/o8f2XIo/Ktl2teRydPHL0QSQWI9sRoPZt8bT2NC6QfUT+iGiKYVaKd7v9fdaWZ9eJbwJtJE1yCrs6jagjxZruP8kV6GxY=,iv:1Qq935FMRnvgAwqZVOrgdSleqpHKWNMrt5lVdJns+7Y=,tag:NJBL7zxKuyWpjUACAZCkyA==,type:str]
    pgp: []
    encrypted_regex: ^(.*[Nn]h.*)$
    version: 3.8.1
