apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: john-carlson
    nh: ENC[AES256_GCM,data:ykLpsg==,iv:HzbJhoEmQNQFUK5eeRSWVwg2KqFVDYxwcqExv4IzQOk=,tag:uzlY7+XtmCNyj/ApNqXY2A==,type:str]
    password: fghj
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10uuwjxr0x0ge4mm2c7u3hm207dwc4jpwe46gtfk2c5kusqtg55ds0jr4uv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidFNVandKOTliZjF2TDRl
            V2NGRUJjOHpCWlJuV1ZlczM2TWVHeHo3NjN3CkkwOG44L0krbDJBMHNHazlUMXV1
            bTNGRGFsaGFzZHlwRVc3elFaZ0J2am8KLS0tIHhUM1ZYYWpVZWl0RTYzOERhOElW
            Rk8xQ2pqM3VSQ3Z3cmw5dXoxN2Y3YncKYIU/7Q9Cgp4RUtPVPQTpN7yxgLOKZw1J
            dT1bi6GHJFhaSB/kVIZGCh/rIUK14CRqbmCyb0fjkIFQib91r8u11g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T08:22:42Z"
    mac: ENC[AES256_GCM,data:SCp0QvndwUvRnpw0jFB7squbKvDiXtbgQUofpleVdSiHqirA8l4Ygq2rPiibzrRgl0Fvo3uopD6RdBABNNa8Xtfw9EUVKmGzH0DmV6Y9IqqTtpquvHAbM+gZG83c/QE3bslMLlLcMroBIV+1gA8Viy+ulOjavlTfc2ZO4t0TgNQ=,iv:qrVeIqZhs9wbZBIDkgyjnSu6qHw72mJ88Q6bMhKtb4s=,tag:W3XdfrbcIsOZdqqloiccMQ==,type:str]
    pgp: []
    encrypted_regex: ^(.*[Nn]h.*)$
    version: 3.8.1
