apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: john-carlson
    nh: ghjk
    password: ENC[AES256_GCM,data:eEdWGQ==,iv:oAGUjusFa9TiirhkvwTJwD1maJcdxVNGveslXqw2GeQ=,tag:TWEL4KX5VV8nDQ2bh/K+aQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10uuwjxr0x0ge4mm2c7u3hm207dwc4jpwe46gtfk2c5kusqtg55ds0jr4uv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaGJia1J1YklMWklTSlFB
            VkFuNDF6NUROOTM2Ykx4Y1BxLy9MZjQ2OVZFClBZMkNsd01pL01wVzlWbURlTG5l
            bUdxOXBjUTMwZG12RjArTnVLdzZCcE0KLS0tIDc3dHNVNFBycWl3U1Eya2FkMW9F
            eTlseVA1dCtYelZoTWg4TDNIb3AzYkUKPeDANWARX0b3vo4iF5AeX0yyPF7ldrV3
            lkzMbEwT5qs8bCpmrxeTglx/dHsjBzQ5uMES4H/u7WKXs3CYgWCg/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T08:03:21Z"
    mac: ENC[AES256_GCM,data:OlxDyEUfBPQqnMgfrpjrRieD3MOiZcI/0epHKxPsd7eRCL9vAQoi+gdJdjcWfYSMgeqb38k8VTKVmF+ZFh68TutrW8kNRhVcFYFCFk+WhaH02MjUI336ScFa2yutiuV4IBzX2YD/lHVMBaIbE+058c09hQqzpfyVunJRCIBTk7k=,iv:PYuvawTDdzYuya0Mq6VZXNdVGcRJV7sAt9pgtbwnWFk=,tag:4WJefImIjaRr//EHPYpgtQ==,type:str]
    pgp: []
    encrypted_regex: ^(.*[Pp]assword.*)$
    version: 3.8.1
