apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: john-carlson
    nh: ghjk
    password: ENC[AES256_GCM,data:TQzXBw==,iv:hLiiY2E1qekfJ9NrWDR6XNObvqBJMsNbR/wjgDZvyog=,tag:uuKVWCdQzVOMRG71y4kRgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109ahnmyr49pq0lq9kkkrvqr65xaj7hxwsksh9gn70dmu9dcau5jqjyam80
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OHM0ZHBZVzVlQ0Y4amlv
            VFVKMWpYUU9jWDVLZUw3VFBCV3VucEEzTGtBCkhPN3V6Ym10akFYOE1kY2VQbjZp
            TWExbGthTi84WVIzU01JM2YvMDBmOHcKLS0tIDRTazBWNGZTMXlWdEE2U2FQZUhS
            R2xzY1AzRnhQRGtXYXhrT1Y0TW1qbGcKDrQOP0PbLLg3HNAwdexw/LsWt/ApkVbK
            kJMqyAY33MaxexfF1W2wPdEEgFQSb/seVE+1L91NzssQ8j8anY44vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T07:37:39Z"
    mac: ENC[AES256_GCM,data:B7FuAEuu3pIj0HVfs0ex1RTi54ISLe5QtX67i4nrpa/kphV+6S6WbALqadDpUeKRi8HL1ziqsvxlWdRMPgA46o1SID28tftoYrIrp+fxCOUx5hrlvQftc8sxdaoMReP5hQDt3y1NyGIZfxJ124jH+9mzI75Kdj3/fL2OUEg73jE=,iv:plmBGXITlcNOhNmF4JDXKhld0+iSXWv1skeP6VUz7FE=,tag:XzC5Al3qaqCCjaAqgU6L/Q==,type:str]
    pgp: []
    encrypted_regex: ^(.*[Pp]assword.*)$
    version: 3.8.1 
