#!/bin/sh


while getopts ":f:" opt; do
  case $opt in
    f) filename="$OPTARG";;
  esac
done

if [ -z "$filename" ]; then
    if [ -f "$file_path" ]; then
        FILES=($file_path)
    else
        echo "invalid file path: $file_path" && exit 1
    fi
else
  
    # find sops.yaml
    # read and find values set to path_regex or filname.regex
    # find all files tha match regex recursively
    
    # awk '/- / {print $2}' your_yaml_file.yaml | while read line; do
    #     echo $line
    # done

    # grep -oP '(?<=- ).*' your_yaml_file.yaml | while read line; do
    #     echo $line
    # done

    FILES=""

fi

for file in $FILES; do
    # exclude .sops config file
    if echo "$file" | grep -Eq '\.sops\.y(a)?ml$'; then
        continue
    fi
    echo "decrypting file: $file"
    sops -d -i "$file"
done

exit 0