#!/bin/sh

# Temporary stash to hold the current state without the staged changes
echo "stashing changes"
git stash save -q --keep-index

# Function to clean up
cleanup() {
    if [ $? -ne 0 ]; then
        echo "something went wrong, falling back to stashed changes..."
        git stash pop -q
    else
        echo "cleaning up..."
        git stash drop -q
    fi
}
trap cleanup EXIT

matches_pattern() {
    local file=$1
    local filename_pattern=$2
    local path_pattern=$3
    [[ "$file" =~ $filename_pattern ]] || [[ "$file" =~ $path_pattern ]]
}

FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.\(yaml\|yml\)$' | grep -v '\.sops\.y\(a\)\?ml$' | grep -E './nested/secret7.yaml')
echo $FILES
# Encrypt and replace each staged file
for file in $FILES; do
    echo "encrypting file: $file"
    sops -e -i "$file"
    if [ $? -ne 0 ]; then
        exit 1
    fi
    git add "$file"
done

exit 0