apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: john-carlson
    nh: ENC[AES256_GCM,data:9Xcf8Q==,iv:2FxiRVNh6VKxRqJwBtRsH/lzTxhNzolIBFeH3SzL3rU=,tag:7ib4shL1JTMjiwchGT2Jog==,type:str]
    password: ENC[AES256_GCM,data:tGY5lFct,iv:4x0RtxCNa7gveoGKuRjxo/HcE+pYJwsYETYAU0s8Amg=,tag:Q1mS8VE+bWI71KtJipig/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18k7h2zrtpd2u4uexz2yx9zhjd0al693rwdryqf0yqz6vpjwg7q5qj5vul0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK25pZUJrYjZ0SXY3ajI4
            YjFLN28xUDFlN05xTi82YkdHRi9adlV3ZURNCmZuSGIzSC9BdS9qMk1WeHVzYUhG
            djIrTGFVK25ScllLYUoxV3oxR3YzSHMKLS0tIEU3Z05zR0dKMEhJM0l5ZEljdEhj
            K2twT0UyQWtlWGJpUmlpdnZ2YUZENEkKgA1NgW01Ta+U9tchq22TTzScRFYB2iji
            VF2czmDJfTTvd+7I0OZhilT2kB+cG94NvpdTBrG7LOZaJjJcQUucdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T19:19:53Z"
    mac: ENC[AES256_GCM,data:T4qFzQj1xel6gaMz7+8wpSLxj2CWxQLbUghiOASnx/GrdDPSOMqs1bZ8xDjD4SXuZ7QUCcYGVPRCD4fEqkYcRkj4O5FzQeq+7YMEghhwV9yE86hnPJBMis8mF6oAjK6d95Zl24qZ9L11nbFCSQjlJ4FGiaZLqIi5loPyatUI0s4=,iv:qsaT4At9mO+J2ywLBuO0i0KIBU2QNgk6d6TyVmpw2ak=,tag:ZnPtXFhOFl2YxbwQqppqYw==,type:str]
    pgp: []
    encrypted_regex: ^(password|(.*[Nn]h.*))$
    version: 3.8.1
