apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: john-carlson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18k7h2zrtpd2u4uexz2yx9zhjd0al693rwdryqf0yqz6vpjwg7q5qj5vul0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcmhoTmM1cktPeHBLTmd2
            UFlyY3MwaUZGZitkVVJWelY0K05RNXAzK0VjCjhnbWpvMk8yWFJNZS9rTlVWRkd5
            dFVscFJRbjA3SmFiSzhxQ3JtRDdhMm8KLS0tIHdvWkFqTml5VmZFTVo4aGZXcTd2
            cmhwSmdLZjJnTkdVTUlsQnI3TUR2SWcKq4Dsh+uG2RIpdR8cAgLVv0lV+nkHIFLJ
            2Utx5iJg7VMxqKsMmb7HUM8gnCaLXLmhD8qGg4cgOnUwnBGvqCtauQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T19:16:23Z"
    mac: ENC[AES256_GCM,data:se5GHkSR1zBOn57X59jdUhWB0VNntZo7kMut4x2w/T+nAua8k/OW5fTuCB/SOv2A8tZVRi27bCdY8uY/HvNmiWM3Y6TQUZA6nRN7hnaYq3kP25Qun4H7qUOS9IPPy9CG6FyvMlcAGR3IFV+6vX8HpGfBFt5pjMIJctrn8SJLr8g=,iv:Y2Vi48GOrHE11ZGRbdbgqN+M4VLgO4EdNYPfesxMyRc=,tag:Y+4kkYsbOh5RdUEyL7dCrA==,type:str]
    pgp: []
    encrypted_regex: ^(password|(.*[Nn]h.*))$
    version: 3.8.1
