apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: john-carlson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18k7h2zrtpd2u4uexz2yx9zhjd0al693rwdryqf0yqz6vpjwg7q5qj5vul0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMEkyQ1FxZ3VGb0JYVEVF
            dUVRZStkTU41ajhLVHFvZ0JOdmpaRi8rU0NVCmJnWTQvVHdhWk5LWkhMSFV4TE1X
            QmxQN21udy8yKy9Ba1lYVEhIeWU5ckEKLS0tIFRLR01welA4SjFhcXdpRnpSeDVF
            NmJTSy9qaVNwdDBrWnlIaFRKaHkwbEUKmd3HiOJSDGdEGcHIIKkHAKQ5Df3Ce1AZ
            5/5qOlDkUf6UMTGsEFRAh1CVyOI08M51Es8FMlTKEkpOiv9D38q0+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T07:57:19Z"
    mac: ENC[AES256_GCM,data:TPN7qCHRINt/WHKDiozbplqU/XYjzzvNE89UOvmke+MNn1oVGeOMEr1b9tVM5xKehMkM+VpjQSHhrSfiWsiSvqtMlhIQpBj2AJI092O0xpYRLlcR1IVPGFzli0+hU9hISdRB1aSGul6IltF4qVBU/MLhEXQgpNKRqHp9ZmTmxwU=,iv:iJ2JQQOprbcAxiYD2aFzaTyCX9Hcs+4Hz9YASq+wiVI=,tag:dO7xnuE0Cp2nFsLu/nyJ0w==,type:str]
    pgp: []
    encrypted_regex: ^(.*[Nn]h.*)$
    version: 3.8.1
