apiVersion: ENC[AES256_GCM,data:ubE=,iv:BWym97HYTnjhWguJ3xxfu2giQBcCneVCnCGiEZpwgPI=,tag:gn+em8bglrjn4v0++A9uAQ==,type:str]
kind: ENC[AES256_GCM,data:AGaQJ6d1,iv:uDktO0uyQSgKhLGUHEHR6f6KHYVqxkOGnEuNu8H/tQ0=,tag:aq8OlwMVZN3FuGtYzPQYDw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3vWhKj5ZyLk=,iv:BvL2hIN3WYlZFRbgzyR8vjIcRgeYVPdstcDB/6OU3WI=,tag:Eu8VlD3k9+z81ATR7In5JA==,type:str]
type: ENC[AES256_GCM,data:gzIRWzfr,iv:qNpdgabgdIPM5i/fwQpGKsXSk6yep8Z45uTHqXEQIo0=,tag:ft+G/RRxB3DGrYkQMFOJyA==,type:str]
data:
    username: ENC[AES256_GCM,data:KoK4r4pTfzxLiS9A,iv:037yh7tRDOgdLEr5BTezQAHijE/Ou+gSS3604aXgDQI=,tag:8kWLNEzBztL196B+x6RoUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18k7h2zrtpd2u4uexz2yx9zhjd0al693rwdryqf0yqz6vpjwg7q5qj5vul0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eHBPdk5HZEE1bGFXa3U1
            TWhYS05SVS9OZGxaK3hrYVlIbWtCWXZvSkN3CmZ3bENHWkw4aFplK3ZjbU95Y0tS
            NXF4aGNiSWttSUZyS2MrcUI5aGt0a1EKLS0tIEs1RW8yV3QrTzlRaHNHdVMrWHp6
            SGwrUjZ3anVHMnJxSGRwNnRNaDd6encKtPM1dWwAvNrABA9t0FRtiExrHgJlDVnY
            yf0m/sPg4XooqfYeOghUXhxntq1PcAmc9WeXwFpsbhWtysrNPK1Sxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T19:11:35Z"
    mac: ENC[AES256_GCM,data:RUAsfxob4joLt1xrW82/Ps8F7NAXbPr0rhknQAubpotlREdjIOxONzF8IHjLHDXivW+9TNmH9QX7/ZUGuoR8WViIUPhtWUhIU67NK1CVWqnssFC21JxHeZT/S2OjTSfpMaLRjAMXUn/I4L9O5sLRfcHS6EupiqLwzOclZgYSX10=,iv:qLhQ6UwKk+TgqNktnTzKmZQCAGdnDY5r5t0uYL76A2Q=,tag:dFhYic/njq4nvIDMPxMSqQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
