apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: john-carlson
    nh: ghjk
    password: ENC[AES256_GCM,data:tCHvDEI+,iv:62Va/ptU3Btnn+ttvdw8+lan/hnx2oJpBXXEJiVI1tg=,tag:F2hxdXEdNrXeF4dxkNqchg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109ahnmyr49pq0lq9kkkrvqr65xaj7hxwsksh9gn70dmu9dcau5jqjyam80
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLREVRNVhWWEtCWUZ0QWF6
            c1pIRTRpNHQrMXFTbHQ3Wm9VV09sV0c5QlFVCkRRVDd5MkpsZTBQMkdCSi9VVU9J
            WldFb2Znc0R4WnBiSVpQaHB1TWRWV0kKLS0tIG1leEVHZHRhOWZUa1pyMTBXSXV3
            bEwxSklpRkR2WDFtSjNjdjZha0JLeE0KSk8XDef1R9J3gCuMuhPrML/FtNVHHLxq
            gUgXux+F3CArl58TdcCh5ZUJ/5ONzd75rw77/iAsMGmhXK5l38SMXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T07:37:54Z"
    mac: ENC[AES256_GCM,data:eeVoELyY+C9d/aYAnQfoWNpXFuBjptzZyh3/n6N252KrtYB8c2zzRV7GBRW7xKJeoJtwBClJdYKS2i94uS0TGGBK/E9o5GoXcjWu+viR0fMrNwdJi2uG8ks+uL+JuYJYNA9jv/W1j3f3kFBFylYS70gyr9A8OyaeVs4QnV15b1M=,iv:oEonCl+0f+6sdXZOjpIkdoASK9ewHN1igltqDVvKhfs=,tag:4wl36E8EKIl2yGlvkVlKKA==,type:str]
    pgp: []
    encrypted_regex: ^(.*[Pp]assword.*)$
    version: 3.8.1
