apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: john-carlson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18k7h2zrtpd2u4uexz2yx9zhjd0al693rwdryqf0yqz6vpjwg7q5qj5vul0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMEdIZXVxR0VJL1FpT3Rr
            ajdhZGtOb1FZRm5sU2NUbm1CWmpHYXZ1YzNFClBiWW82b0VDc1FNUlBSMHZyZzhv
            M2l6aTFocmM5eEh0K3BaQzR6S3R6ODAKLS0tIGhDWkhWQVBUWjhiSXRsblNCSGp1
            YmZkbDNxckxHMTloMHl1SjRRWnV1SzAKvvLjjAi2f1NlchfJ7vmkXdUuR5F4MDpY
            LLeYhP87KcgRXScwtYDtHqvqz0uF+Izf2xewiw3GAKQmx2Ho37B+sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T22:46:43Z"
    mac: ENC[AES256_GCM,data:rKYM2R1jPjgAUMCKtnmR1KYkdhw+ysSV778UxycDiRNAc3M6KBO8/ui5K9S/angsVWnWFoHNMmwtF5z97RGEe8uamyjq7iDuwwmCXIsHOPoi4thgoEhu8YAPOy6dSDlr6hzQK+7A1IRlv6glktFWc5YCxm+iu5xtd+OCSNUL1F4=,iv:7ADGuxbm8N0QW9J07D+JPHjI5Jn5HBjdQc3OyEVyW7U=,tag:XutgL01OumJgmBNsVk6npQ==,type:str]
    pgp: []
    encrypted_regex: ^(.*[Nn]h.*)$
    version: 3.8.1
